gpn-prototypes/vega-shell

.github/workflows/build-static.yaml
package.json
src/index.ejs
webpack.config.js
yarn.lock

VEGA-416: Настроить деплой vega-shell на стенд

---

src/index.ejs

VEGA-428: Интегрировать vega-auth с vega-shell

---

package.json
src/index.ejs
src/utils/graphql-client/graphql-client.ts
src/utils/graphql-client/index.ts
src/utils/identity/identity.ts
src/vega-shell.ts
yarn.lock

VEGA-501: Прикрутить создание клиента в vega-shell

---

src/index.ejs

Jira issue: VEGA-440
Подключен модуль vega-sp
Исправлен редирект на проекты https://github.com/gpn-prototypes/vega-sp/pull/36
Мержить после https://github.com/gpn-prototypes/vega-sp/pull/35

VEGA-440: Интегрировать vega-sp с vega-shell

---

src/index.ejs

VEGA-435: Интегрировать vega-header с vega-shell

---

package.json
src/index.ejs
src/utils/identity/identity.ts
src/vega-shell.ts
yarn.lock

Jira issue: VEGA-447
https://jira.csssr.io/browse/VEGA-447
- добавил новую структуру роутов
- временно подключил vega-rb из ветки develop

VEGA-447: Интегрировать vega-rb с vega-shell

---

package.json
src/index.ejs
webpack.config.js
yarn.lock

Правки в сборке

---

src/index.ejs
webpack.config.js

Добавлены изменения для размещения в Yandex Cloud

---

src/vega-shell.ts

VEGA-621: Заменить ручку авторизации

---

webpack.config.js

fix(webpack): поправил publicPath

---

webpack.config.js

https://github.com/gpn-prototypes/vega-header/pull/44
https://github.com/gpn-prototypes/vega-sp/pull/59
https://github.com/gpn-prototypes/vega-auth/pull/70

VEGA-630: Прокинуть переменные окружения в сборку

---

src/index.ejs
webpack.config.js

- для сборки под YC был указан путь до import-map vega-rb
- в сборку добавлены переменные окружения

Исправление сборки под YC

---

src/utils/identity/identity.ts
src/vega-shell.ts

https://github.com/gpn-prototypes/vega-header/pull/45

VEGA-632: Исправить редирект на страницу проектов после логина

---

src/index.ejs

Обновить csp

---

src/utils/graphql-client/graphql-client.ts

VEGA-407: Интеграция с бэком "Просмотр и редактирование проекта"

---

package.json
yarn.lock

Обновить версию gpn-prototypes/vega-ui

---

package.json
src/components/Loader/Loader.css
src/components/Loader/Loader.tsx
src/components/Loader/index.ts
src/index.ejs
src/vega-shell.ts
yarn.lock

VEGA-594: Реализовать страницу загрузки системы

---

src/utils/api-client/api-client.test.ts
src/utils/api-client/api-client.ts
src/utils/identity/identity.test.ts
src/utils/identity/identity.ts

fix(auth): исправить выброс ошибки при авторизации

---

src/index.ejs

fix(build): исправить BASE_URL до статики при деплое в YC

---

src/utils/graphql-client/graphql-client.ts
webpack.config.js

fix(apollo-cache): добавить функцию получения id | vid

---

src/index.ejs

https://github.com/gpn-prototypes/vega-rb/pull/33
https://github.com/gpn-prototypes/vega-sp/pull/75

VEGA-637: Убрать вертикальный скролл, если контент помещается на страницу

---

src/utils/graphql-client/graphql-client.ts
src/vega-shell.ts

VEGA-644: Исправить редирект при удалении токена перед отправкой формы

---

src/index.ejs

https://jira.konakov.tv/browse/VEGA-2601
Добавлены импорты single-spa для интеграции
* пересоздал - ветка без feature

Vega 2601: Интеграция vega-lc в vega-shell 

---

src/vega-shell.ts

VEGA-645: Исправить редирект на пустую страницу по нажатию Назад

---

src/components/Snackbar/Snackbar.css
src/components/Snackbar/Snackbar.tsx
src/components/Snackbar/index.ts
src/components/index.ts
src/index.ejs
src/utils/notifications/index.ts
src/utils/notifications/notifications.test.ts
src/utils/notifications/notifications.ts
src/vega-shell.ts
stylelint.config.js

VEGA-520: Создать центр уведомлений в веге

---

src/vega-shell.ts

VEGA-656: Исправить появление лоадера в Описании проекта, если РБ недоступна

---

yarn.lock

Обновить vega-ui

---

package.json
src/index.ejs
yarn.lock

* feat: intergration vega-lc to vega-shell
* fix: port to 9005

Vega 2601: Интеграция vega-lc в vega-shell  (#47)

---

package.json
yarn.lock

VEGA-702: Обновить vega-ui

---

app-config/index.js
src/index.ejs
webpack.config.js

VEGA-719: Избавиться от упоминаний стендов в репозиториях

---

.github/workflows/build-static.yaml
src/index.ejs
webpack.config.js

Изменения касаются только нашего ci

Добавить переменные окружения в ci

---

src/utils/graphql-client/graphql-client.test.ts
src/utils/graphql-client/graphql-client.ts
src/utils/graphql-client/mocks.ts

VEGA-636: Добавить поддержку эндпоинта для проекта

---

src/components/Snackbar/Snackbar.tsx
src/vega-shell.ts

VEGA-663: Добавить вывод уведомления при ошибочной загрузке приложения (РБ, ФЭМ, КЛ)

---

package.json
webpack.config.js
yarn.lock

Обновил vega-ui, вернул опцию в webpack

VEGA-728: Избавить от дублирования стилей vega-ui

---

src/components/Application/Application.tsx
src/components/Error/Error.css
src/components/Error/ErrorView.tsx
src/vega-shell.tsx

VEGA-595: Реализовать страницу ошибки 500

---

src/utils/graphql-client/graphql-client.test.ts
src/utils/graphql-client/graphql-client.ts

VEGA-751: Исследовать ошибку 400 при переходе в РБ и КЛ

---

src/components/ApplicationRoutes/ApplicationRoutes.tsx
src/index.ejs

VEGA-742: Интегрировать vega-fem

---

src/App.css
src/components/ApplicationRoutes/ApplicationRoutes.tsx
src/index.ejs

VEGA-746: Убрать вертикальный скролл, если контент помещается на страницу

---

src/index.ejs

VEGA-752: Восстановить фавиконку

---

package.json
yarn.lock

chore(global): Обновление VEGA-UI

---

package.json
yarn.lock

Обновить версию vega-ui

---

src/index.ejs

VEGA-769: Исправить наложения поля в фокусе на хедер

---

src/Applications.tsx
src/app-context.tsx
src/components/Application/Application.tsx
src/components/ApplicationRoutes/ApplicationRoutes.tsx

VEGA-780: [В МАСТЕР] Не отображать хедер на страницах 404 и 500

---

package.json
yarn.lock

VEGA-692: Добавить data-test-id для страницы создания проекта

---

src/services/message-bus/types.ts
src/services/message-bus/worker.ts
src/vega-shell.tsx

- добавлена опция `broadcast`, чтобы шарить событие на другие вкладки. По умолчанию `false`
- `self` по умолчанию сделана `true`

VEGA-795: Исправить отображение 404 и 500 во всех открытых вкладках

---

src/services/graphql-client/graphql-client.ts

VEGA-789: Локализовать текст ошибки при порче токена

---

src/services/identity/tokenHandlers.test.ts
src/services/identity/tokenHandlers.ts
yarn.lock

VEGA-802: Написать тесты для утилит из tokenHandlers.ts

---

src/components/Snackbar/Snackbar.css

VEGA-653: Исправить отображение уведомления о закрытии, если наименование проекта длинное и без пробелов

---

package.json
yarn.lock

VEGA-825: Обновить Consta и Vega-UI

---

.github/workflows/coverage.yaml
jest.config.js
package.json

https://jira.csssr.io/browse/VEGA-803

VEGA-803: Настроить test coverage для vega-shell

---

.github/workflows/update-vega-ui.yml

VEGA-828: Создать экшен для обновления vega-ui

---

.github/workflows/coverage.yaml

chore(ci): исправить coverage workflow

---

package.json
yarn.lock

[VEGA-3014] chore(deps): Обновление vega-ui

---

src/services/api-client/api-client.test.ts
src/services/api-client/api-client.ts
src/services/graphql-client/graphql-client.test.ts
src/services/identity/__mocks__/tokenHandlers.ts
src/services/identity/identity.test.ts
src/services/identity/identity.ts
src/vega-shell.tsx

VEGA-717: Написать тесты для новой авторизации

---

jest.config.js
package.json
setup-tests.ts
src/services/graphql-client/graphql-client.test.ts
src/services/graphql-client/graphql-client.ts
src/services/graphql-client/links.test.ts
src/services/graphql-client/mocks.ts
src/services/identity/tokenHandlers.ts
src/test-utils/MockLocalStorage.ts
src/test-utils/make-promise.ts

VEGA-811: Покрыть тестами GraphQLClient

---

src/services/graphql-client/graphql-client.test.ts
src/services/graphql-client/graphql-client.ts
src/services/graphql-client/links.test.ts

VEGA-733: Доработать обработку 404

---

src/components/Header/HeaderView.tsx

test(test-id): добавление test-id в блок юзера

---

.eslintrc.js
graphql.schema.json
src/__generated__/types.ts
src/components/Header/Header.tsx
src/components/Header/__generated__/get-project-name.tsx

VEGA-890: Убрать хедер со страниц 404 и 500

---

src/services/graphql-client/graphql-client.ts
src/services/graphql-client/links.test.ts

Jira issue: [VEGA-809](https://jira.csssr.io/browse/VEGA-809)

VEGA-809: Доработать авторизацию

---

package.json
src/components/Error/ErrorView.test.tsx
src/components/Error/ErrorView.tsx
yarn.lock

VEGA-863: Покрыть тестами страницу ошибки

---

graphql.schema.json
src/__generated__/types.ts
src/components/ApplicationRoutes/ApplicationRoutes.tsx
src/components/AuthForm/AuthForm.tsx
src/components/AuthForm/index.ts
src/components/AuthPage/AuthPage.tsx
src/components/AuthPage/index.ts
src/components/Header/__generated__/get-project-name.tsx

VEGA-891: Реализовать поведение уведомлений при переходах на другие страницы

---

.github/workflows/update-vega-ui.yml
global.d.ts
src/components/Application/Application.test.tsx
src/components/Application/Application.tsx
src/components/Application/application-handle-error.test.tsx
src/components/Loader/Loader.tsx
src/services/notifications/notifications.test.ts
src/services/notifications/notifications.ts
src/testing/SystemJS.ts
src/testing/index.ts
src/testing/react-testing-library.tsx
tsconfig.json

VEGA-861: Покрыть тестами компонент Application

---

setup-tests.ts
src/components/Application/Application.test.tsx
src/components/Application/application-handle-error.test.tsx
src/components/ApplicationRoutes/ApplicationRoutes.test.tsx
src/components/ApplicationRoutes/ApplicationRoutes.tsx
src/components/Error/ErrorView.tsx
src/components/Error/index.ts
src/services/identity/identity.ts
src/services/identity/index.ts
src/testing/react-testing-library.tsx

VEGA-862: Покрыть тестами компонент ApplicationRoutes

---

package.json
yarn.lock

chore(components): Обновление версии vega-ui

---

src/services/graphql-client/graphql-client.test.ts
src/services/graphql-client/project-diff-resolver/combined-fetch-result.test.ts
src/services/graphql-client/project-diff-resolver/combined-fetch-result.ts
src/services/graphql-client/project-diff-resolver/error.ts
src/services/graphql-client/project-diff-resolver/project-diff-resolver-link.test.ts
src/services/graphql-client/project-diff-resolver/project-diff-resolver-link.ts
src/services/graphql-client/project-diff-resolver/project-diff-resolver.ts
src/services/graphql-client/project-diff-resolver/project-diff-resolving-operation.ts

VEGA-864: Покрыть тестами конкурентный доступ

---

src/components/Error/Error.css
src/services/graphql-client/graphql-client.ts

VEGA-750: Исправить положение лоадера на странице 500

---

graphql.schema.json
src/app/shell.ts
src/components/ApplicationRoutes/ApplicationRoutes.tsx
src/components/Header/HeaderView.tsx

VEGA-753: Отображать подтверждение об отмене создания проекта при нажатии кнопки Выйти

---

ci/Dockerfile
ci/build-entrypoint.sh
ci/build.sh
graphql.schema.json
src/__generated__/types.ts

Common Jira: [VEGA-3194](https://jira.vegaspace.tk/browse/VEGA-3194)
CSSSR Jira: [VEGA-915](https://jira.csssr.io/browse/VEGA-915)

VEGA-3194: [FE] Адаптация сборок для периметра КСПД

---

package.json
yarn.lock

chore(global): Обновление версии vega-ui

---

src/components/ApplicationRoutes/ApplicationRoutes.test.tsx
src/components/AuthForm/AuthForm.test.tsx
src/components/AuthForm/AuthForm.tsx
src/components/AuthPage/AuthPage.test.tsx
src/components/AuthPage/AuthPage.tsx
src/components/AuthPage/index.ts
src/testing/authorize-user.ts
src/testing/index.ts
src/testing/react-testing-library.tsx

VEGA-867: Покрыть тестами AuthPage

---

src/components/Application/Application.test.tsx
src/components/BaseHeader/BaseHeaderMenu/BaseHeaderMenu.test.tsx
src/components/BaseHeader/BaseHeaderMenu/BaseHeaderMenu.tsx
src/components/BaseHeader/BaseHeaderMenu/BaseHeaderMenuItem.tsx
src/components/BaseHeader/BaseHeaderNav/BaseHeaderNav.tsx
src/components/Header/Header.test.tsx
src/components/Header/HeaderView.test.tsx
src/components/Header/HeaderView.tsx
src/testing/index.ts
src/testing/react-testing-library.test.tsx
src/testing/render-with-server-error.tsx
src/testing/wait-requests.ts

VEGA-866: Покрыть тестами Header

---

src/components/Snackbar/Snackbar.test.tsx
src/components/Snackbar/Snackbar.tsx
src/services/notifications/notifications.test.ts
src/services/notifications/notifications.ts

VEGA-950: Допокрыть тестами Notifications и Snackbar

---

.github/dependabot.yml

VEGA-940: Добавить dependabot в vega-shell

---

package.json
yarn.lock

VEGA-906: Добавить data-testid для подтверждения об отмене создания проекта

---

ci/Dockerfile
ci/build-entrypoint.sh
ci/build.sh
ci/npmrc-template

Исправление build докер - Добавлен флаг REBUILD для пересборки, сборка сделана постоянно (с кэшем)
https://jira.vegaspace.tk/browse/VEGA-3237

[VEGA-3237] ci: common ci build modify

---

src/components/Application/Application.test.tsx
src/components/Application/Application.tsx
src/components/Application/ErrorBoundery.test.tsx
src/components/Application/ErrorBoundery.tsx
src/components/ApplicationRoutes/ApplicationRoutes.test.tsx
src/components/AuthForm/AuthForm.test.tsx
src/components/AuthPage/AuthPage.test.tsx
src/components/Header/Header.test.tsx
src/components/Header/HeaderView.test.tsx
src/testing/react-testing-library.tsx
src/testing/render-with-server-error.tsx

VEGA-942: Вернуть уведомление об ошибке загрузки модуля 

---

.github/workflows/continuous-integration.yml
ci/build-entrypoint.sh
src/components/Application/Application.test.tsx
src/components/Application/ErrorBoundery.test.tsx

VEGA-905: Добавить в игнор кодогенерацию в vega-shell

---

.eslintrc.js
.github/workflows/coverage.yaml
src/app/__tests__/project-version-sync.test.ts
src/app/shell.ts
src/services/current-project/current-project.test.ts
src/services/current-project/current-project.ts
src/services/current-project/index.ts
src/services/graphql-client/cache.test.ts
src/services/graphql-client/cache.ts
src/services/graphql-client/graphql-client.test.ts
src/services/graphql-client/graphql-client.ts
src/services/graphql-client/links.test.ts
src/services/graphql-client/project-version-syncer/endpoint-strategies/abstract-endpoint-strategy.ts
src/services/graphql-client/project-version-syncer/endpoint-strategies/common-endpoint-strategy.ts
src/services/graphql-client/project-version-syncer/endpoint-strategies/create-endpoint-strategy.ts
src/services/graphql-client/project-version-syncer/endpoint-strategies/index.ts
src/services/graphql-client/project-version-syncer/endpoint-strategies/project-endpoint-strategy.ts
src/services/graphql-client/project-version-syncer/endpoint-strategies/strategies.test.ts
src/services/graphql-client/project-version-syncer/index.ts
src/services/graphql-client/project-version-syncer/project-operations.test.ts
src/services/graphql-client/project-version-syncer/project-operations.ts
src/services/graphql-client/project-version-syncer/project-version-syncer-link.ts
src/services/graphql-client/project-version-syncer/utils.test.ts
src/services/graphql-client/project-version-syncer/utils.ts
src/services/graphql-client/utils.test.ts
src/services/graphql-client/utils.ts
src/testing/configure-shell.ts
src/testing/index.ts
src/testing/react-testing-library.tsx

Jira issue CSSSR: https://jira.csssr.io/browse/VEGA-911
Jira issue VEGA: https://jira.vegaspace.tk/browse/VEGA-3255
Что нужно для интеграции:
- добавить ко всем graphql запросам корневой __typename для получения `Query` и `Mutation`
- заменить `graphqlClient.query` на `graphqlClient.watchQuery`
- убрать `fetchPolicy: 'no-cache'` для тех запросов, где нужно автоматическое обновление проекта
- добавить в запрос мутации поле `version` (обязательно должно идти после мутации)

VEGA-911: Добавить обработку версии проекта в обвязке

---

src/services/graphql-client/graphql-client.test.ts
src/services/graphql-client/graphql-client.ts
src/services/graphql-client/links.test.ts

VEGA-922: исправить обработку ошибки 401 в graphql клиенте

---

graphql.schema.json
schema.graphql
src/services/api-client/api-client.test.ts
src/services/api-client/api-client.ts

VEGA-957: Отображать код ошибки в уведомлениях авторизации

---

ci/build-entrypoint.sh
ci/build.sh

https://jira.vegaspace.tk/browse/VEGA-3243
https://git.konakov.tv/vega2/vega-builder-automation/-/merge_requests/61
-  добавлены env переменные для генерации схемы в сборку
-  игнор ошибок удаления докер контейнера

[VEGA-3243] ci: Исправление общей сборки YC

---

.github/workflows/build-static.yaml
.github/workflows/continuous-integration.yml
.github/workflows/coverage.yaml
.graphqlrc.yaml
codegen.yml
package.json
yarn.lock

VEGA-971: Убрать graphql.schema.json из реп

---

package.json
src/components/ApplicationRoutes/ApplicationRoutes.test.tsx
src/components/ApplicationRoutes/ApplicationRoutes.tsx
src/components/AuthForm/AuthForm.test.tsx
src/components/AuthForm/AuthForm.tsx
src/components/AuthForm/index.ts
src/components/AuthPage/AuthPage.test.tsx
src/components/AuthPage/AuthPage.tsx
src/components/AuthPage/index.ts
src/services/identity/identity.test.ts
src/services/identity/identity.ts
src/services/identity/index.ts
src/testing/configure-shell.ts
yarn.lock

VEGA-810: Покрыть тестами авторизацию в vega-shell

---

README.md
src/services/message-bus/README.md

VEGA-959: Документация шины событий

---

README.md
src/services/current-project/README.md

VEGA-963: Документация сервиса для работы с текущим проектом

---

ci/build-entrypoint.sh
ci/build.sh

Jira issue: VEGA-3243
https://jira.vegaspace.tk/browse/VEGA-3243
Добавление параметров, необходимых для сборки на YC

[VEGA-3243] fix(ci): Добавление параметров, необходимых для сборки на YC

---

src/components/Snackbar/Snackbar.tsx
src/services/notifications/notification/notification.test.ts
src/services/notifications/notification/notification.ts
src/services/notifications/notifications.test.ts
src/services/notifications/notifications.ts

…граничение на вывод 2х нотификаций
Jira issue: VEGA-953

VEGA-953: Реализовать скрытие содержания уведомлений

---

README.md
src/services/notifications/README.md
src/services/notifications/notifications.ts

VEGA-960: Документация уведомлений

---

README.md
src/services/graphql-client/README.md
src/services/graphql-client/project-diff-resolver/README.md

Jira issue: VEGA-961 https://jira.csssr.io/browse/VEGA-961

VEGA-961: Документация конкурентного доступа

---

package.json
yarn.lock

VEGA-3372: Обновление vega-ui

---

jest.config.js
package.json
yarn.lock

Jest-junit reporter plugin added
- [ x] PR: назначен исполнитель PR и указаны нужные лейблы
- [ x] PR: проверен diff, ничего лишнего в PR не попало
- [ x] PR: есть описание изменений или приложена ссылка на задачу с описанием, оставлены пояснительные комментарии к diff

Added jest-junit reporter

---

src/components/Error/ErrorView.test.tsx

Jira issue: VEGA-3425
При прохождении тестов в консоли отображаются системные ошибки:
-  выполнение обновления стейта размонтированного компонента
- не найден window.open
- добавил сброс значения таймеров перед выполнением каждого теста
- добавил мок для функции open
Стенд: http://ltumoyakov-3425-lanit-vega-builder.code013.org
[Основной ПР - VEGA-3425](https://github.com/gpn-prototypes/vega-shell/pull/188)
http://jenkins-remote-ci-gpn-vega-builder.code013.org:8081/job/STAND-TOOLBOX/job/scenario-tests-on-demand/761/

[VEGA-3425] test(ErrorView): Исправление ошибок в тестах

---

src/services/graphql-client/cache.ts
src/services/graphql-client/project-diff-resolver/README.md
src/services/graphql-client/project-diff-resolver/project-diff-resolver-link.test.ts
src/services/graphql-client/project-diff-resolver/project-diff-resolver-link.ts
src/services/graphql-client/project-diff-resolver/project-diff-resolver.ts
src/services/graphql-client/project-diff-resolver/project-diff-resolving-operation.ts
src/services/graphql-client/utils.test.ts
src/services/graphql-client/utils.ts

Jira issue: VEGA-3402
Стенд: http://ltumoyakov-3402-lanit-vega-builder.code013.org
Добавлено детальное слияние версий
https://wiki.vegaspace.tk/pages/viewpage.action?pageId=43713993
[VEGA-3557](https://jira.vegaspace.tk/browse/VEGA-3557) [VEGA-3699](https://jira.vegaspace.tk/browse/VEGA-3699)
http://jenkins-remote-ci-gpn-vega-builder.code013.org:8081/job/STAND-TOOLBOX/job/scenario-tests-on-demand/934/

[VEGA-3402] feat(global): Добавление детального слияния версий
